#!/bin/bash

CHAIN_ID=signerchain
devenv () {

  start () {
    # Reset the build directory
    rm -rf build

    # Build tmsigner and put in Path
    make build
    mv ./build/tmsigner $GOBIN

    # Build simd locally
    ./scripts/build-simd.bash local skip

    # Configure and start the two node network
    ./scripts/two-node-net.bash skip $CHAIN_ID build

    # Start the signer in the foreground
    tmsigner start 
  }

  stop () {
    echo "stopping simd instances..."
    pkill -9 simd
    echo "stopping tmsigner instance..."
	pkill -9 tmsigner
  }

  commands () {
    cat <<-EOF
sample commands:
  start -> start the sample environment
  stop -> stop the sample environment
EOF
  }

  case $1 in
    start)
      start
      ;;
    stop)
      stop
      ;;
    *)
      commands
      ;;
  esac
}

devenv $1